[package]
name = "micro_http_async"
version = "0.0.2"
authors = ["Dimitri Bobkov <bobkov.dimitri@gmail.com>"]
edition = "2018"
description = "A small, lightweight crate using async to serve web pages or webapis with high performance and low overhead."
readme = "README.md"
keywords = ["async", "http", "performance", "small"]
license = "MIT"
repository = "https://github.com/dimitribobkov/micro-http-async"
documentation = "https://docs.rs/micro_http_async"

[dependencies]
async-trait = "0.1.4" # Allows us to use async in traits

# Third party async
[dependencies.tokio]
version = "1.1.1" 
features = ["full"]